[phases.setup]
nixPkgs = ["python310", "nodejs_18"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python manage.py migrate && python manage.py collectstatic --noinput --clear && gunicorn Gestion_stock.wsgi --bind 0.0.0.0:$PORT"
